### ISSUE TITLE
关于多地区配置

### ISSUE THREAD

**Issue by yehuzhucha** [startkkkkkk/Beijing_Daxuexi_Simple#13]
大佬好，请问有时间可以写一个河北省使用的吗😋

**Comment by 123heihuhu** [comment]
改对应的学习链接就行了

**Comment by yehuzhucha** [comment]
> 改对应的学习链接就行了

愿闻其详，希望大佬不吝赐教

**Comment by startkkkkkk** [comment]
> > 改对应的学习链接就行了
> 
> 愿闻其详，希望大佬不吝赐教

你可以看下github上其他省大学习的项目，每个省系统和对应的链接不一样

**Comment by daning66** [comment]
有辽宁的没
