### ISSUE TITLE
Error: The process '/usr/bin/sh' failed with exit code 128

### ISSUE THREAD

**Issue by dong-design** [startkkkkkk/Beijing_Daxuexi_Simple#19]
前两次能运行成功  以后就都不行了    但是no update的 action可以运行成功
![Screenshot_20220515_093927](https://user-images.githubusercontent.com/67950595/168453806-2d46fc0b-d4c7-48a8-905d-05aba22c5481.jpg)

**Comment by startkkkkkk** [comment]
有修改了就不能用自动更新的分支了，这个readme也有提到
