### ISSUE TITLE
支持多用户吗

### ISSUE THREAD

**Issue by T-Atlas** [startkkkkkk/Beijing_Daxuexi_Simple#2]

**Comment by James-Harden-13-R** [comment]
+1

**Comment by startkkkkkk** [comment]
用Actions的话，只能用secret输入账号信息，多用户就得是一个有结构输入，配置存在一定难度，能配置的几乎也可以自己改了，主脚本里开头加个逻辑就行；Github Actions结果是公开的也是个问题，多账户无法安全地直接打印部分失败的结果

**Comment by startkkkkkk** [comment]
#3
