### ISSUE TITLE
action 运行失败

### ISSUE THREAD

**Issue by surreyskahn** [startkkkkkk/Beijing_Daxuexi_Simple#22]
actions/checkout@v2, aormsby/fork-sync-with-upstream-action@v3.1, and actions/setup-python@v1 are not allowed to be used in surreyskahn/Beijing_Daxuexi_Simple. Actions in this workflow must be: within a repository owned by surreyskahn.

**Comment by startkkkkkk** [comment]
Refer to https://github.com/orgs/community/discussions/26609.
是不是设置了 “Allow local actions only”

**Comment by surreyskahn** [comment]
已解决，特别感谢！
