### ISSUE TITLE
学习相关问题

### ISSUE THREAD

**Issue by TogetherRolle** [startkkkkkk/Beijing_Daxuexi_Simple#23]
你好，想请教下学习方法，我刚刚入门会使用基本语法，但感觉缺乏很多系统性知识 想请教下如何学习。比如说让自己的代码能在actions运行，pycharm生成requirements.txt等功能之前都不知道。看了你编程的大为震撼，请指教！

**Comment by startkkkkkk** [comment]
其实我干的事情也是蛮入门的hh就看别人的东西学的
