### ISSUE TITLE
最近一次的程序运行报错

### ISSUE THREAD

**Issue by VinsonZhangS** [startkkkkkk/Beijing_Daxuexi_Simple#24]
在Actions中的Job部分：
在显示User1登录成功后便开始报错。具体的Python报错是在request中的get报错
在Summary中的Annotation中显示为build报错：
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, aormsby/Fork-Sync-With-Upstream-action, actions/setup-python, actions/checkout
因为之前就已经Fork+Star了，并且在自己的Action中运行成功多次了，突然报错有点不知所措，不知道是什么问题。

**Comment by startkkkkkk** [comment]
接口改变，已解决
