### ISSUE TITLE
api 疑似失效

### ISSUE THREAD

**Issue by SakuraLaurel** [startkkkkkk/Beijing_Daxuexi_Simple#31]
我之前是靠类似本仓库的方法，手动点击链接完成学习的，并在国庆期间预学习了本周内容。今天准备预学习下周内容，发现链接失效，然后找到了这个仓库。非常感谢作者为我们做的这些，但我发现了两个疑似无法修复的问题：

1、之前是可以预学习的，比如9月就可以把91期92期都学完；但是今天我把本仓库在本地跑了跑，发现无论如何都无法预学习未来的内容，总是会返回本期内容。

2、更重要的是，使用这类方法，我自己可以查到自己完成了学习，但团支书那边显示我没有。因为我自己之前就有了学习记录，所以无法复现这个问题。我怀疑这个方法已经失效了。

希望其他人尤其是团支书确认一下是否存在这些问题，及时补票，避免大家超过学习时限。

**Comment by SakuraLaurel** [comment]
另外，是怎么发现api更改是从get请求变成了post请求的呀，真的太优秀了

**Comment by startkkkkkk** [comment]
https://m.bjyouth.net/qndxx/index.html#/pages/home/studyrecord 这个里面是看得到记录，组织也是正确的吗

**Comment by SakuraLaurel** [comment]
看得到记录，组织也是正确的。但不知道是不是因为我在系统改变之前的那次学习生效了。

**Comment by startkkkkkk** [comment]
把视频播了一遍也没看到其他明显的请求🤔倒是数据类型有点点不一样，但如果那个界面能显示就应该证明也没事。我自己也没有团支书账号所以也没法测试

**Comment by SakuraLaurel** [comment]
麻烦你了。这个我记得，我是可以自己查到记录的，但是去找团支书，他看到后台记录里没有我。
我放过视频之后，我的记录没有变化，后台却显示我学习了。
另外，产生学习记录可能是在冒出第一个问题之前，我播到这个地方，团支书恰好查了一下，发现我学了，我就没继续播了。

**Comment by startkkkkkk** [comment]
除非他们刻意想反脚本，不然大概是数据类型的问题，毕竟这个存在拼写错误和莫名其妙变量名的系统不转换数据还是蛮可能的😂

**Comment by 123heihuhu** [comment]
> 我之前是靠类似本仓库的方法，手动点击链接完成学习的，并在国庆期间预学习了本周内容。今天准备预学习下周内容，发现链接失效，然后找到了这个仓库。非常感谢作者为我们做的这些，但我发现了两个疑似无法修复的问题：
> 
> 1、之前是可以预学习的，比如9月就可以把91期92期都学完；但是今天我把本仓库在本地跑了跑，发现无论如何都无法预学习未来的内容，总是会返回本期内容。
> 
> 2、更重要的是，使用这类方法，我自己可以查到自己完成了学习，但团支书那边显示我没有。因为我自己之前就有了学习记录，所以无法复现这个问题。我怀疑这个方法已经失效了。
> 
> 希望其他人尤其是团支书确认一下是否存在这些问题，及时补票，避免大家超过学习时限。

**Comment by marinero4972** [comment]
同样发现了自己有记录，但是团支书那边没有记录的问题

**Comment by 000lbh** [comment]
我刚刚试了，团支书跟我说他那里有记录

**Comment by LeandroDing** [comment]
刚刚试了，显示Error: raise Exception('貌似自己这显示完成了，但实际上没有？建议自己检查下(尤其是有团支书账号可以看到情况的)，然后可以在issue#31里反馈下') 团支书后台没有记录

**Comment by wangyian-me** [comment]
刚刚试了，显示Error: raise Exception('貌似自己这显示完成了，但实际上没有？建议自己检查下(尤其是有团支书账号可以看到情况的)，然后可以在issue#31里反馈下') 团支书后台**有记录**

**Comment by 123heihuhu** [comment]
我有团支书账号，但是当前期已完成学习，下周二可以反馈

**Comment by startkkkkkk** [comment]
我测试了一下现在是可以的，确实是数据类型的问题，如果有人当前版本还是有问题再开issue吧

**Comment by SakuraLaurel** [comment]
@startkkkkkk 我发现之前我们班群里流传的链接，是从其他团支部来的，团组织org_id和我所属的不一致。可能是因为这个原因，有的记录能被团支书查到，有的记录不能。

**Comment by startkkkkkk** [comment]
> 我这里还是不行
> 
> > 刚刚试了，显示Error: raise Exception('貌似自己这显示完成了，但实际上没有？建议自己检查下(尤其是有团支书账号可以看到情况的)，然后可以在issue#31里反馈下') 团支书后台没有记录
> 
> 我这里刚刚试过，还是没有显示，我在想是不是因为之前我点过那个速通链接，多点了很多导致留下了不少空白的完成记录。但现在速通链接已经寄了，所以即使后台看不到完成记录，但在这里还是检测为已完成，所以就没有速通？是不是要等到空白记录都填上，这个程序才能发挥作用？

新的期数应该可以，以前的应该是这个情况，如果不想手动解决可以把文件主体那块换成一个循环补下以前的

**Comment by z-rrr** [comment]
> > 我这里还是不行
> > > 刚刚试了，显示Error: raise Exception('貌似自己这显示完成了，但实际上没有？建议自己检查下(尤其是有团支书账号可以看到情况的)，然后可以在issue#31里反馈下') 团支书后台没有记录
> > 
> > 
> > 我这里刚刚试过，还是没有显示，我在想是不是因为之前我点过那个速通链接，多点了很多导致留下了不少空白的完成记录。但现在速通链接已经寄了，所以即使后台看不到完成记录，但在这里还是检测为已完成，所以就没有速通？是不是要等到空白记录都填上，这个程序才能发挥作用？
> 
> 新的期数应该可以，以前的应该是这个情况，如果不想手动解决可以把文件主体那块换成一个循环补下以前的
