### ISSUE TITLE
关于青年大学习账号和密码

### ISSUE THREAD

**Issue by xmexg** [startkkkkkk/Beijing_Daxuexi_Simple#44]
我在微信青春山东公众号上进行青年大学习，自动使用微信登录，没有设置过账号和密码，我应该在哪里设置账户和密码？

**Comment by zyh364267040** [comment]
你的这个问题解决了吗，通过公众号进行青年大学习，可以登录吗？

**Comment by xmexg** [comment]
没有,一周一次,每次进去看1秒视频就完事,手动应该是最节省时间的
