### ISSUE TITLE
登录失败报错

### ISSUE THREAD

**Issue by z379035389** [startkkkkkk/Beijing_Daxuexi_Simple#53]
Traceback (most recent call last):
  File "/home/zephyr/Beijing_Daxuexi_Simple/study.py", line 22, in study
    r'src="(/site/captcha.+)" alt=', touch.text)[0]
IndexError: list index out of range

**Comment by z379035389** [comment]
发现是并发太快导致服务器可能屏蔽了 设置延迟即可。

**Comment by surreyskahn** [comment]
如何设置每个账号之间的延迟，有大佬能讲讲吗

**Comment by startkkkkkk** [comment]
加了间隔
