### ISSUE TITLE
关于github action的政策问题

### ISSUE THREAD

**Issue by Misaka-Aki** [startkkkkkk/Beijing_Daxuexi_Simple#9]
根据github的有关规定，像这种利用action跑脚本的行为是违规的，有很多人的仓库都被封了，但似乎每两个月给你发邮件提醒的时候重新启动action可以避免被封。
所以想请问一下大佬，有没有兴趣做一个本地运行或者云函数的版本，这样可以避免未来发生问题

**Comment by chf12345** [comment]
云函数的话自己用腾讯云的弄一下就好了吧，每个月有免费额度的https://console.cloud.tencent.com/scf/list?rid=1&ns=default

**Comment by startkkkkkk** [comment]
两个月的提示是因为inactive，如果自己修改的话可以考虑每次随便改个文件然后actions workflow里加个commit，这个repo里面workflow(因为有一些fork开了更新)改不了了
